In [1]:
import pandas as pd

In [2]:
stats = pd.read_csv("player_mvp_stats.csv")

In [3]:
stats

,Unnamed: 0,Player,Age,Team,Pos,G,GS,MP,FG,FGA,...,Pts Max,Share,Tm,W,L,W/L%,GB,PS/G,PA/G,SRS
0,0,Doc Rivers,29,Atlanta Hawks,PG,79,79,32.7,5.6,12.9,...,0.0,0.00,ATL,43,39,0.524,18.0,109.8,109.0,0.72
1,1,Dominique Wilkins,31,Atlanta Hawks,SF,81,81,38.0,9.5,20.2,...,960.0,0.03,ATL,43,39,0.524,18.0,109.8,109.0,0.72
2,2,Duane Ferrell,25,Atlanta Hawks,SF,78,2,14.9,2.2,4.6,...,0.0,0.00,ATL,43,39,0.524,18.0,109.8,109.0,0.72
3,3,Gary Leonard,23,Atlanta Hawks,C,4,0,2.3,0.0,0.0,...,0.0,0.00,ATL,43,39,0.524,18.0,109.8,109.0,0.72
4,4,John Battle,28,Atlanta Hawks,SG,79,2,23.6,5.0,10.9,...,0.0,0.00,ATL,43,39,0.524,18.0,109.8,109.0,0.72
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16377,16377,Kyshawn George,21,Washington Wizards,SG,68,38,26.5,3.0,8.0,...,0.0,0.00,WAS,18,64,0.220,23.0,108.0,120.4,-12.14
16378,16378,Malcolm Brogdon,32,Washington Wizards,PG,24,13,23.5,4.3,10.0,...,0.0,0.00,WAS,18,64,0.220,23.0,108.0,120.4,-12.14
16379,16379,Marcus Smart,30,Washington Wizards,PG,34,7,20.0,3.0,7.6,...,0.0,0.00,WAS,18,64,0.220,23.0,108.0,120.4,-12.14
16380,16380,Richaun Holmes,31,Washington Wizards,PF,31,7,17.2,2.9,4.5,...,0.0,0.00,WAS,18,64,0.220,23.0,108.0,120.4,-12.14
16381,16381,Tristan Vukcevic,21,Washington Wizards,C,35,1,14.7,3.4,6.9,...,0.0,0.00,WAS,18,64,0.220,23.0,108.0,120.4,-12.14

In [4]:
del stats["Unnamed: 0"]

In [5]:
stats

,Player,Age,Team,Pos,G,GS,MP,FG,FGA,FG%,...,Pts Max,Share,Tm,W,L,W/L%,GB,PS/G,PA/G,SRS
0,Doc Rivers,29,Atlanta Hawks,PG,79,79,32.7,5.6,12.9,0.435,...,0.0,0.00,ATL,43,39,0.524,18.0,109.8,109.0,0.72
1,Dominique Wilkins,31,Atlanta Hawks,SF,81,81,38.0,9.5,20.2,0.470,...,960.0,0.03,ATL,43,39,0.524,18.0,109.8,109.0,0.72
2,Duane Ferrell,25,Atlanta Hawks,SF,78,2,14.9,2.2,4.6,0.489,...,0.0,0.00,ATL,43,39,0.524,18.0,109.8,109.0,0.72
3,Gary Leonard,23,Atlanta Hawks,C,4,0,2.3,0.0,0.0,NaN,...,0.0,0.00,ATL,43,39,0.524,18.0,109.8,109.0,0.72
4,John Battle,28,Atlanta Hawks,SG,79,2,23.6,5.0,10.9,0.461,...,0.0,0.00,ATL,43,39,0.524,18.0,109.8,109.0,0.72
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16377,Kyshawn George,21,Washington Wizards,SG,68,38,26.5,3.0,8.0,0.372,...,0.0,0.00,WAS,18,64,0.220,23.0,108.0,120.4,-12.14
16378,Malcolm Brogdon,32,Washington Wizards,PG,24,13,23.5,4.3,10.0,0.433,...,0.0,0.00,WAS,18,64,0.220,23.0,108.0,120.4,-12.14
16379,Marcus Smart,30,Washington Wizards,PG,34,7,20.0,3.0,7.6,0.393,...,0.0,0.00,WAS,18,64,0.220,23.0,108.0,120.4,-12.14
16380,Richaun Holmes,31,Washington Wizards,PF,31,7,17.2,2.9,4.5,0.647,...,0.0,0.00,WAS,18,64,0.220,23.0,108.0,120.4,-12.14
16381,Tristan Vukcevic,21,Washington Wizards,C,35,1,14.7,3.4,6.9,0.496,...,0.0,0.00,WAS,18,64,0.220,23.0,108.0,120.4,-12.14

In [6]:
pd.isnull(stats).sum()

Player        0
Age           0
Team          0
Pos           0
G             0
GS            0
MP            0
FG            0
FGA           0
FG%          68
3P            0
3PA           0
3P%        2163
2P            0
2PA           0
2P%         118
eFG%         68
FT            0
FTA           0
FT%         603
ORB           0
DRB           0
TRB           0
AST           0
STL           0
BLK           0
TOV           0
PF            0
PTS           0
Year          0
Pts Won       0
Pts Max       0
Share         0
Tm            0
W             0
L             0
W/L%          0
GB            0
PS/G          0
PA/G          0
SRS           0
dtype: int64

In [7]:
stats[pd.isnull(stats["FT%"])][["Player", "FTA"]]

                Player  FTA
72         Tom Hovasse  0.0
87         Tim Kempton  0.0
89      Anthony Miller  0.0
148         Andy Panko  0.0
155         Ira Bowman  0.0
...                ...  ...
16322   Tremont Waters  0.0
16330     Devon Dotson  0.0
16336   Jordan Schakel  0.0
16350   Hamidou Diallo  0.0
16371  Jalen McDaniels  0.0

[603 rows x 2 columns]

In [8]:
stats = stats.fillna(0)

In [9]:
stats.columns

Index(['Player', 'Age', 'Team', 'Pos', 'G', 'GS', 'MP', 'FG', 'FGA', 'FG%',
       '3P', '3PA', '3P%', '2P', '2PA', '2P%', 'eFG%', 'FT', 'FTA', 'FT%',
       'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS', 'Year',
       'Pts Won', 'Pts Max', 'Share', 'Tm', 'W', 'L', 'W/L%', 'GB', 'PS/G',
       'PA/G', 'SRS'],
      dtype='object')

In [10]:
predictors = ['Age', 'G', 'GS', 'MP', 'FG', 'FGA', 'FG%',
       '3P', '3PA', '3P%', '2P', '2PA', '2P%', 'eFG%', 'FT', 'FTA', 'FT%',
       'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS', 'Year',
       'W', 'L', 'W/L%', 'GB', 'PS/G', 'PA/G', 'SRS']

In [11]:
train = stats[stats["Year"] < 2025]

In [12]:
test = stats[stats["Year"] == 2025]

In [13]:
from sklearn.linear_model import Ridge

reg = Ridge(alpha=.1)

In [14]:
reg.fit(train[predictors], train["Share"])

Ridge(alpha=0.1)

In [15]:
predictions = reg.predict(test[predictors])

In [16]:
predictions = pd.DataFrame(predictions, columns=["predictions"], index=test.index)

In [17]:
predictions

       predictions
542       0.012821
543       0.005299
544      -0.008407
545      -0.014035
546       0.016020
...            ...
16377    -0.019938
16378     0.012663
16379    -0.000041
16380     0.001312
16381     0.016740

[569 rows x 1 columns]

In [18]:
combination = pd.concat([test[["Player", "Share"]], predictions], axis=1)

In [19]:
combination

                 Player  Share  predictions
542        Caris LeVert    0.0     0.012821
543        Clint Capela    0.0     0.005299
544     Daeqwon Plowden    0.0    -0.008407
545     Dominick Barlow    0.0    -0.014035
546       Dyson Daniels    0.0     0.016020
...                 ...    ...          ...
16377    Kyshawn George    0.0    -0.019938
16378   Malcolm Brogdon    0.0     0.012663
16379      Marcus Smart    0.0    -0.000041
16380    Richaun Holmes    0.0     0.001312
16381  Tristan Vukcevic    0.0     0.016740

[569 rows x 3 columns]

In [20]:
combination.sort_values("Share", ascending=False).head(10)

                        Player  Share  predictions
11100  Shai Gilgeous-Alexander  0.913     0.171855
4119              Nikola Jokić  0.787     0.192677
8980     Giannis Antetokounmpo  0.470     0.229978
1103              Jayson Tatum  0.311     0.114073
2989          Donovan Mitchell  0.074     0.073422
7451              LeBron James  0.016     0.108751
4660           Cade Cunningham  0.012     0.087302
9510           Anthony Edwards  0.012     0.075132
5235             Stephen Curry  0.002     0.069749
2991               Evan Mobley  0.001     0.083820

In [21]:
from sklearn.metrics import mean_squared_error

mean_squared_error(combination["Share"], combination["predictions"])

0.002481804853956328

In [22]:
combination = combination.sort_values("Share", ascending=False)
combination["Rk"] = list(range(1,combination.shape[0]+1))

In [23]:
combination.head(10)

                        Player  Share  predictions  Rk
11100  Shai Gilgeous-Alexander  0.913     0.171855   1
4119              Nikola Jokić  0.787     0.192677   2
8980     Giannis Antetokounmpo  0.470     0.229978   3
1103              Jayson Tatum  0.311     0.114073   4
2989          Donovan Mitchell  0.074     0.073422   5
7451              LeBron James  0.016     0.108751   6
4660           Cade Cunningham  0.012     0.087302   7
9510           Anthony Edwards  0.012     0.075132   8
5235             Stephen Curry  0.002     0.069749   9
2991               Evan Mobley  0.001     0.083820  10

In [24]:
combination = combination.sort_values("predictions", ascending=False)
combination["Predicted_Rk"] = list(range(1,combination.shape[0]+1))

In [25]:
combination.head(20)

                        Player  Share  predictions   Rk  Predicted_Rk
8980     Giannis Antetokounmpo  0.470     0.229978    3             1
4119              Nikola Jokić  0.787     0.192677    2             2
11100  Shai Gilgeous-Alexander  0.913     0.171855    1             3
7452               Luka Dončić  0.000     0.136083  258             4
3556             Anthony Davis  0.000     0.128464  121             5
10235          Zion Williamson  0.000     0.123708  361             6
1103              Jayson Tatum  0.311     0.114073    4             7
14405        Victor Wembanyama  0.000     0.110486  513             8
7451              LeBron James  0.016     0.108751    6             9
11645           Paolo Banchero  0.000     0.100007  412            10
12754             Kevin Durant  0.000     0.092770  448            11
10796       Karl-Anthony Towns  0.000     0.092012  368            12
12213              Joel Embiid  0.000     0.089510  427            13
4660           Cade Cunningham  0.012     0.087302    7            14
10794            Jalen Brunson  0.001     0.086794   12            15
8978            Damian Lillard  0.000     0.085018  306            16
2991               Evan Mobley  0.001     0.083820   10            17
6897              James Harden  0.001     0.083757   11            18
11094           Jalen Williams  0.000     0.077468  392            19
9510           Anthony Edwards  0.012     0.075132    8            20

In [26]:
combination.sort_values("Share", ascending=False).head(10)

                        Player  Share  predictions  Rk  Predicted_Rk
11100  Shai Gilgeous-Alexander  0.913     0.171855   1             3
4119              Nikola Jokić  0.787     0.192677   2             2
8980     Giannis Antetokounmpo  0.470     0.229978   3             1
1103              Jayson Tatum  0.311     0.114073   4             7
2989          Donovan Mitchell  0.074     0.073422   5            21
7451              LeBron James  0.016     0.108751   6             9
9510           Anthony Edwards  0.012     0.075132   8            20
4660           Cade Cunningham  0.012     0.087302   7            14
5235             Stephen Curry  0.002     0.069749   9            26
6897              James Harden  0.001     0.083757  11            18

In [27]:
def find_ap(combination):
    actual = combination.sort_values("Share", ascending=False).head(5)
    predicted = combination.sort_values("predictions", ascending=False)
    ps = []
    found = 0
    seen = 1
    for index, row in predicted.iterrows():
        if row["Player"] in actual["Player"].values:
            found+=1
            ps.append(found/seen)
        seen+=1
    return sum(ps)/ len(ps)

In [28]:
find_ap(combination)

0.7619047619047619

In [29]:
years = list(range(1991,2026))

In [30]:
aps = []
all_predictions = []
for year in years[5:]:
    train = stats[stats["Year"] < year]
    test = stats[stats["Year"] == year]
    reg.fit(train[predictors], train["Share"])
    predictions = reg.predict(test[predictors])
    predictions = pd.DataFrame(predictions, columns=["predictions"], index=test.index)
    combination = pd.concat([test[["Player", "Share"]], predictions], axis=1)
    all_predictions.append(combination)
    aps.append(find_ap(combination))

In [31]:
sum(aps) / len(aps)

0.7214101517482118

In [32]:
def add_ranks(combination):
    combination = combination.sort_values("Share", ascending=False)
    combination["Rk"] = list(range(1,combination.shape[0]+1))
    combination = combination.sort_values("predictions", ascending=False)
    combination["Predicted_Rk"] = list(range(1,combination.shape[0]+1))
    combination["Diff"] = combination["Rk"] - combination["Predicted_Rk"]
    return combination

In [33]:
ranking = add_ranks(all_predictions[1])
ranking[ranking["Rk"] < 6].sort_values("Diff", ascending=False)

               Player  Share  predictions  Rk  Predicted_Rk  Diff
15267     Karl Malone  0.857     0.192316   1             2    -1
1973   Michael Jordan  0.832     0.167579   2             3    -1
4216       Grant Hill  0.327     0.128603   3             6    -3
7970     Tim Hardaway  0.207     0.059936   4            20   -16
1601        Glen Rice  0.117     0.033083   5            53   -48

In [34]:
def is_mvp_eligible(row):
    if row["Year"] < 2023:
        return True  # no hard rule
    return row["G"] >= 65  # simple approximation
    
stats = stats[stats.apply(is_mvp_eligible, axis=1)]

In [35]:
def backtest(stats, model, years, predictors):
    aps = []
    all_predictions = []
    for year in years[5:]:
        train = stats[stats["Year"] < year]
        test = stats[stats["Year"] == year]
        model.fit(train[predictors], train["Share"])
        predictions = model.predict(test[predictors])
        predictions = pd.DataFrame(predictions, columns=["predictions"], index=test.index)
        combination = pd.concat([test[["Player", "Share", "Year"]], predictions], axis=1)
        combination = add_ranks(combination)
        all_predictions.append(combination)
        aps.append(find_ap(combination))
    return sum(aps)/len(aps), aps, pd.concat(all_predictions)

In [36]:
mean_ap, aps, all_predictions = backtest(stats, reg, years, predictors)

In [37]:
mean_ap

0.7274801373181974

In [38]:
all_predictions[all_predictions["Rk"] <= 5].sort_values("Diff").head(10)

                 Player  Share  Year  predictions  Rk  Predicted_Rk  Diff
9706         Jason Kidd  0.712  2002     0.028201   2            52   -50
1601          Glen Rice  0.117  1997     0.033083   5            53   -48
12438        Steve Nash  0.839  2005     0.034094   1            45   -44
13503   Peja Stojaković  0.228  2004     0.036261   4            38   -34
12456        Steve Nash  0.739  2006     0.054124   1            34   -33
2226        Joakim Noah  0.258  2014     0.046977   4            37   -33
4350   Chauncey Billups  0.344  2006     0.052695   5            35   -30
12676        Chris Paul  0.138  2021     0.072298   5            33   -28
12471        Steve Nash  0.785  2007     0.074417   2            21   -19
7970       Tim Hardaway  0.207  1997     0.059936   4            20   -16

In [39]:
pd.concat([pd.Series(reg.coef_), pd.Series(predictors)], axis=1).sort_values(0, ascending=False)

           0     1
13  0.120998  eFG%
29  0.029856  W/L%
18  0.029621   DRB
10  0.017175    2P
17  0.016138   ORB
21  0.012845   STL
12  0.011154   2P%
22  0.010134   BLK
15  0.008767   FTA
25  0.007939   PTS
20  0.007131   AST
5   0.005271   FGA
4   0.001081    FG
30  0.000272    GB
0   0.000218   Age
32  0.000166  PA/G
27  0.000142     W
1   0.000087     G
2  -0.000010    GS
26 -0.000206  Year
28 -0.000313     L
33 -0.000352   SRS
31 -0.000977  PS/G
7  -0.001863    3P
24 -0.002091    PF
3  -0.004028    MP
14 -0.004804    FT
16 -0.006044   FT%
9  -0.009408   3P%
23 -0.009465   TOV
8  -0.010187   3PA
11 -0.017345   2PA
19 -0.021903   TRB
6  -0.193724   FG%

In [40]:
stat_ratios = stats.groupby("Year")[["PTS", "AST", "STL", "BLK", "3P"]].transform(lambda x: x / x.mean())

stats[["PTS_T", "AST_R", "STL_R", "BLK_R", "3P_R"]] = stat_ratios

In [41]:
predictors += ["PTS_T", "AST_R", "STL_R", "BLK_R", "3P_R"]

In [42]:
dfpredictors = predictors.copy()

In [43]:
dfpredictors += ["TS%", "Team_WinRank", "TopSeed"]

In [44]:
mean_ap, aps, all_predictions = backtest(stats, reg, years, predictors)
mean_ap

0.7229420408620552

In [45]:
stats["NPos"] = stats["Pos"].astype("category").cat.codes
stats["NTm"] = stats["Tm"].astype("category").cat.codes

In [46]:
import numpy as np
# add new features to df

df = stats.copy()
# --- Shooting efficiency ---
# True Shooting % = PTS / (2 * (FGA + 0.44 * FTA))
df["TS%"] = df["PTS"] / (2 * (df["FGA"] + 0.44 * df["FTA"]))
df["TS%"] = df["TS%"].replace([np.inf, -np.inf], np.nan).fillna(0)

# Rank teams by win percentage within each season
team_ranks = (
    df.groupby(["Year", "Tm"])["W/L%"]
      .first()  # one value per team-year
      .groupby("Year")
      .rank(ascending=False)
)

# Map back to player rows
df["Team_WinRank"] = df.set_index(["Year", "Tm"]).index.map(team_ranks)

# Mark top 2 seeds
df["TopSeed"] = (df["Team_WinRank"] <= 2).astype(int)

In [47]:
df

,Player,Age,Team,Pos,G,GS,MP,FG,FGA,FG%,...,PTS_T,AST_R,STL_R,BLK_R,3P_R,NPos,NTm,TS%,Team_WinRank,TopSeed
0,Doc Rivers,29,Atlanta Hawks,PG,79,79,32.7,5.6,12.9,0.435,...,1.696115,2.012367,2.613685,1.350437,5.608983,2,0,0.529543,13.0,0
1,Dominique Wilkins,31,Atlanta Hawks,SF,81,81,38.0,9.5,20.2,0.470,...,2.890090,1.544374,2.063435,1.800583,5.099075,3,0,0.555222,13.0,0
2,Duane Ferrell,25,Atlanta Hawks,SF,78,2,14.9,2.2,4.6,0.489,...,0.680678,0.327595,0.550249,0.675219,0.000000,3,0,0.556569,13.0,0
3,Gary Leonard,23,Atlanta Hawks,C,4,0,2.3,0.0,0.0,0.000,...,0.055793,0.000000,0.000000,0.675219,0.000000,0,0,0.568182,13.0,0
4,John Battle,28,Atlanta Hawks,SG,79,2,23.6,5.0,10.9,0.461,...,1.517576,1.263579,0.825374,0.225073,1.019815,4,0,0.537125,13.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16362,Tyus Jones,27,Washington Wizards,PG,66,66,29.3,4.9,10.1,0.489,...,0.897670,2.372307,1.352941,0.526718,1.060137,2,35,0.578927,29.0,0
16364,Alex Sarr,19,Washington Wizards,C,67,67,27.1,4.9,12.4,0.394,...,1.010580,0.767310,0.786047,2.992916,1.037208,0,35,0.481481,29.0,0
16367,Bub Carrington,19,Washington Wizards,PG,82,57,30.0,3.7,9.1,0.401,...,0.761822,1.406735,0.786047,0.598583,1.102033,2,35,0.513627,29.0,0
16374,Jordan Poole,25,Washington Wizards,SG,68,68,29.4,6.7,15.5,0.432,...,1.593606,1.438706,1.459801,0.798111,2.268891,4,35,0.593859,29.0,0
16377,Kyshawn George,21,Washington Wizards,SG,68,38,26.5,3.0,8.0,0.372,...,0.676311,0.799281,1.122924,1.396694,1.102033,4,35,0.504875,29.0,0

In [48]:
stats

,Player,Age,Team,Pos,G,GS,MP,FG,FGA,FG%,...,PS/G,PA/G,SRS,PTS_T,AST_R,STL_R,BLK_R,3P_R,NPos,NTm
0,Doc Rivers,29,Atlanta Hawks,PG,79,79,32.7,5.6,12.9,0.435,...,109.8,109.0,0.72,1.696115,2.012367,2.613685,1.350437,5.608983,2,0
1,Dominique Wilkins,31,Atlanta Hawks,SF,81,81,38.0,9.5,20.2,0.470,...,109.8,109.0,0.72,2.890090,1.544374,2.063435,1.800583,5.099075,3,0
2,Duane Ferrell,25,Atlanta Hawks,SF,78,2,14.9,2.2,4.6,0.489,...,109.8,109.0,0.72,0.680678,0.327595,0.550249,0.675219,0.000000,3,0
3,Gary Leonard,23,Atlanta Hawks,C,4,0,2.3,0.0,0.0,0.000,...,109.8,109.0,0.72,0.055793,0.000000,0.000000,0.675219,0.000000,0,0
4,John Battle,28,Atlanta Hawks,SG,79,2,23.6,5.0,10.9,0.461,...,109.8,109.0,0.72,1.517576,1.263579,0.825374,0.225073,1.019815,4,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16362,Tyus Jones,27,Washington Wizards,PG,66,66,29.3,4.9,10.1,0.489,...,113.7,123.0,-9.29,0.897670,2.372307,1.352941,0.526718,1.060137,2,35
16364,Alex Sarr,19,Washington Wizards,C,67,67,27.1,4.9,12.4,0.394,...,108.0,120.4,-12.14,1.010580,0.767310,0.786047,2.992916,1.037208,0,35
16367,Bub Carrington,19,Washington Wizards,PG,82,57,30.0,3.7,9.1,0.401,...,108.0,120.4,-12.14,0.761822,1.406735,0.786047,0.598583,1.102033,2,35
16374,Jordan Poole,25,Washington Wizards,SG,68,68,29.4,6.7,15.5,0.432,...,108.0,120.4,-12.14,1.593606,1.438706,1.459801,0.798111,2.268891,4,35
16377,Kyshawn George,21,Washington Wizards,SG,68,38,26.5,3.0,8.0,0.372,...,108.0,120.4,-12.14,0.676311,0.799281,1.122924,1.396694,1.102033,4,35

In [49]:
def top1_top5_test(predict):
    top1_correct = 0
    top5_correct = 0
    for year, group in predict.groupby("Year"):
        actual_mvp_rank = group.loc[group["Rk"] == 1, "Player"].values[0]
        predicted_ranks = group.set_index("Player")["Predicted_Rk"]
        predicted_rank_of_mvp = predicted_ranks[actual_mvp_rank]

        # Top-1
        if predicted_rank_of_mvp == 1:
            top1_correct += 1
        # Top-5
        if predicted_rank_of_mvp <= 5:
            top5_correct += 1

    n_years = predict["Year"].nunique()
    return top1_correct / n_years, top5_correct / n_years

In [50]:
def top10_mean_abs_rank_diff(predict):
    top_players = predict[predict["Rk"] <= 10]
    mean_top10_diff = top_players["Diff"].abs().mean()
    return mean_top10_diff

In [51]:
models = ["Baseline (Ridge Regression)", "RandomForestRegressor", "XGBoost LambdaRank"]
test_results = ["mean_ap", "top1", "top5", "mean_abs_rank_diff"]

data = []

In [52]:
mean_ap, aps, all_predictions = backtest(stats, reg, years, predictors)
mean_ap

0.7229420408620552

In [53]:
top1_top5_test(all_predictions)

(0.36666666666666664, 0.8)

In [54]:
top10_mean_abs_rank_diff(all_predictions)

np.float64(6.923333333333333)

In [55]:
mean_ap, aps, all_predictions = backtest(df, reg, years, dfpredictors)
mean_ap
bl_data = []
bl_data.append(mean_ap)

In [56]:
top1, top5 = top1_top5_test(all_predictions)
bl_data.append(top1)
bl_data.append(top5)

In [57]:
top10_mean_abs_rank_diff(all_predictions)
bl_data.append(top10_mean_abs_rank_diff(all_predictions))

In [58]:
data.append(bl_data)

In [59]:
from sklearn.ensemble import RandomForestRegressor

rf = RandomForestRegressor(n_estimators=500, random_state=1, min_samples_split=5)

rf_mean_ap, rf_aps, rf_all_predictions = backtest(stats, rf, years, predictors)
mean_ap

0.7178914230421672

In [60]:
top1_top5_test(rf_all_predictions)

(0.5666666666666667, 0.9333333333333333)

In [61]:
top10_mean_abs_rank_diff(rf_all_predictions)

np.float64(5.1433333333333335)

In [62]:
rf_mean_ap_df, rf_aps_df, rf_all_predictions_df = backtest(df, rf, years, dfpredictors)
rf_mean_ap_df
rf_data = []
rf_data.append(rf_mean_ap_df)

In [63]:
top1, top5 = top1_top5_test(rf_all_predictions_df)
rf_data.append(top1)
rf_data.append(top5)

In [64]:
top10_mean_abs_rank_diff(rf_all_predictions_df)
rf_data.append(top10_mean_abs_rank_diff(rf_all_predictions_df))
data.append(rf_data)

In [ ]:
import xgboost as xgb
import pandas as pd
import numpy as np

def backtest_xgb(stats, years, predictors, params, num_boost_round=300):
    aps = []
    all_predictions = []

    for year in years[5:]:
        train = stats[stats["Year"] < year]
        test = stats[stats["Year"] == year]

        X_train = train[predictors]
        y_train = train["Share"].values
        groups_train = train.groupby("Year").size().to_list()

        dtrain = xgb.DMatrix(X_train, label=y_train)
        dtrain.set_group(groups_train)

        model = xgb.train(params, dtrain, num_boost_round=num_boost_round)

        X_test = test[predictors]
        dtest = xgb.DMatrix(X_test)
        preds = model.predict(dtest)

        combination = test[["Player", "Share", "Year"]].copy()
        combination["predictions"] = preds

        combination = add_ranks(combination)

        aps.append(find_ap(combination))

        all_predictions.append(combination)

    mean_ap = sum(aps)/len(aps)
    return mean_ap, aps, pd.concat(all_predictions)

In [66]:
# XGBoost LambdaRank parameters
params = {
    "objective": "rank:pairwise",
    "eval_metric": "ndcg@5",
    "eta": 0.1,
    "max_depth": 6,
    "subsample": 0.8,
    "colsample_bytree": 0.8,
    "tree_method": "hist"
}

In [67]:
# Test without df predicitors
xgb_mean_ap, xgb_aps, xgb_predictions = backtest_xgb(stats, years, predictors, params, num_boost_round=300)
xgb_mean_ap

0.8122198756409282

In [68]:
top1_top5_test(xgb_predictions)

(0.6333333333333333, 0.9666666666666667)

In [69]:
top10_mean_abs_rank_diff(xgb_predictions)

np.float64(3.58)

In [70]:
# Test with df predictors
xgb_mean_ap, xgb_aps, xgb_predictions = backtest_xgb(df, years, dfpredictors, params, num_boost_round=300)
xgb_mean_ap
xgb_data = []
xgb_data.append(xgb_mean_ap)

In [71]:
xgb_mean_ap

0.816995496706023

In [72]:
top1, top2 = top1_top5_test(xgb_predictions)
xgb_data.append(top1)
xgb_data.append(top2)

In [73]:
top10_mean_abs_rank_diff(xgb_predictions)
xgb_data.append(top10_mean_abs_rank_diff(xgb_predictions))
data.append(xgb_data)

In [74]:
df = pd.DataFrame(data, index=models, columns=test_results)
df

                              mean_ap      top1      top5  mean_abs_rank_diff
Baseline (Ridge Regression)  0.717891  0.466667  0.833333            7.070000
RandomForestRegressor        0.747561  0.533333  0.900000            5.136667
XGBoost LambdaRank           0.816995  0.600000  0.966667            3.403333